stages:
  - install
  - notify

install:
  stage: install
  only:
    - prod-VeoVeo
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - Gitlab-Runner
  image:
    name: armandofcom/python-node13-aws:latest
    entrypoint: [""]
  services:
    - armandofcom/python-node13-aws:latest
  cache:
   paths:
    - node_modules
  script:
    - npm config set registry https://nexus.guajitech.com/repository/npm/
    - npm install
    - npm install -g typescript@4.6.2
    - npm run build --prod
    - aws s3 sync --acl public-read --metadata-directive REPLACE --cache-control max-age=0,public dist/tienda-angular-b2b s3://cloudfront-www.veoveofashion.com --delete
    - aws cloudfront create-invalidation --distribution-id E3IC3Y9FW43HZE --paths "/*"
    - curl -X POST "https://api.cloudflare.com/client/v4/zones/37729262bc2d7d99e38e6dcc915637be/purge_cache" -H "X-Auth-Email:guajiritossrl@gmail.com" -H "X-Auth-Key:96ea36c8747ec2f985b68d6c1682d24ab5dd3" -H "Content-Type:application/json" --data '{"purge_everything":true}'
    - echo "DEPLOYED SUCCESSFULLY"

success:
  tags:
    - Gitlab-Runner
  image: alpine:latest
  stage: notify
  script:
    - apk add --update git curl
    - wget https://raw.githubusercontent.com/armandofcom/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - /bin/ash ./send.sh success $WEBHOOK_URL
  when: on_success

failure:
  tags:
    - Gitlab-Runner
  image: alpine:latest
  stage: notify
  script:
    - apk add --update git curl
    - wget https://raw.githubusercontent.com/armandofcom/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - /bin/ash ./send.sh failure $WEBHOOK_URL
  when: on_failure
