image: nikolaik/python-nodejs:latest

cache:
  paths:
    - node_modules

deploy_multiagency:
  only:
    - tienda-online-b2b-mercedes
  when: always
  script:
    - npm install
    - npm run build --prod
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -b ~/bin/aws
    - export PATH=~/bin:$PATH
    - export AWS_ACCESS_KEY_ID=AKIA5KQSOEMEWVT2T327
    - export AWS_SECRET_ACCESS_KEY=cJJ+bkej/mJNZXF5CymIVr8CA2mjI7ixfeApjkMj
    - export AWS_DEFAULT_REGION=us-east-1
    - aws s3 sync --acl public-read --metadata-directive REPLACE --cache-control max-age=1200,public dist/tienda-angular-b2b s3://mercedes.cubanearme.com --delete
    - aws cloudfront create-invalidation --distribution-id E23HEZVFCB8G99 --paths "/*"
