image: nikolaik/python-nodejs:latest

cache:
  paths:
    - node_modules

deploy_tcp:
  only:
    - tienda-online-b2b-mibulevar
  when: always
  script:
    - npm install
    - npm install typescript@4.1.3 -s
    - npm run build --prod
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -b ~/bin/aws
    - export PATH=~/bin:$PATH
    - aws s3 sync --acl public-read --metadata-directive REPLACE --cache-control max-age=1200,public dist/tienda-angular-b2b s3://www.mibulevar.com --delete
    - aws cloudfront create-invalidation --distribution-id E2SDTK0QPMLF3V --paths "/*"
