image: nikolaik/python-nodejs:latest

cache:
  paths:
    - node_modules

deploy_adminexperiencias2:
  only:
    - tienda-online-b2b-marlin
  when: always
  script:
    - npm install
    - npm run build --prod
    - curl "https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz" -o "aliyun-cli-linux-latest-amd64.tgz"
    - tar xzvf aliyun-cli-linux-latest-amd64.tgz
    - cp aliyun /usr/local/bin
    - aliyun configure set --profile DeployProfile --mode AK --region $ALIYUN_DEFAULT_REGION --access-key-id $ALIYUN_ACCESS_KEY_ID --access-key-secret $ALIYUN_SECRET_ACCESS_KEY
    - curl "http://gosspublic.alicdn.com/ossutil/1.6.18/ossutil64" -o "ossutil64"
    - chmod 755 ossutil64
    - cp ossutil64 /usr/local/bin
    - ./ossutil64 config -e oss-us-east-1.aliyuncs.com -i $ALIYUN_ACCESS_KEY_ID -k $ALIYUN_SECRET_ACCESS_KEY -L EN -c ~/ossutil64config
    - ./ossutil64 rm oss://tienda-marinasmarlin/ -r -f -c ~/ossutil64config
    - ./ossutil64 cp -r dist/tienda-angular-b2b oss://tienda-marinasmarlin -u --meta=Cache-Control:max-age=600 -c ~/ossutil64config
    - aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://tienda.marinasmarlin.com/
