export const environment = {
  production: true,
  apiUrl: 'https://api.mibulevar.com/v1/',
  imageUrl: 'https://api.mibulevar.com/v1/',
  defaultLanguage: 'es',
  currencyInternational: 'USD',
  version: '1.2.0',
  url: 'https://www.mibulevar.com',
  urlAboutUs: 'https://www.mibulevar.com',
  address: 'Bazar Familia / Quinta Avenida,18204, Playa, La Habana.',
  localDatabaseUsers: true,
  adminService: 'https://admin.mibulevar.com/',
  mainDomain: '.mibulevar.com',
  tokenBusiness: '',
};
