export const environment = {
  production: true,
  apiUrl: 'https://apimercedes.cubanearme.com/v1/',
  imageUrl: 'https://apimercedes.cubanearme.com/v1/',
  apiUrlRepositoy: 'https://apimercedes.cubanearme.com/v1/',
  defaultLanguage: 'es',
  version: '1.2.0',
  url: 'https://mercedes.cubanearme.com',
  urlAboutUs: 'https://mercedes.cubanearme.com',
  address: 'Mercedes SA / Quinta Avenida,18204, Playa, La Habana.',
  localDatabaseUsers: true,
  uploadDigitalProduct: false,
  uploadServicesProduct: false,
  adminService: 'http://adminmercedes.cubanearme.com/',
  mainDomain: '.cubanearme.com',
};
